# Generated by Django 5.2.17 on 2026-09-17 13:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compatibility_score', models.FloatField(default=0.0)),
                ('llm_explanation', models.TextField(blank=True, help_text='RAG-generated explanation of the match.', null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='jobs.jobdescription')),
                ('matched_skills', models.ManyToManyField(blank=True, related_name='matched_in_analyses', to='core.skill')),
                ('missing_skills', models.ManyToManyField(blank=True, related_name='missing_in_analyses', to='core.skill')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
            ],
        ),
    ]
