# Generated by Django 5.2.17 on 2026-09-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='ats_report',
            field=models.JSONField(blank=True, help_text='ATS document-quality check results.', null=True),
        ),
    ]
