# Generated by Django 5.2.17 on 2026-09-17 13:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('raw_text', models.TextField(blank=True)),
                ('candidate_name', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_skills', models.ManyToManyField(blank=True, related_name='resumes', to='core.skill')),
            ],
        ),
    ]
